apiVersion: v1
kind: Secret
metadata:
  name: pagamento-service-secret
  namespace: tcc
stringData:
  MERCADO_PAGO_ACCESS_TOKEN: "${MERCADO_PAGO_ACCESS_TOKEN}"
  DB_URL: "jdbc:postgresql://pagamento-rds.cspsguim81hr.us-east-1.rds.amazonaws.com:5432/pagamento"
  DB_USER: "${DB_USER}"
  DB_PASS: "${DB_PASS}"